name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']
    name: Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Pre Ci
        run: yarn run preci

      - name: Install Dependencies
        run: yarn run ci

      - name: Run ESLint
        run: yarn run lint

      - name: Test Build
        run: yarn run build